trigger:
- develop

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build Docker Image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/TrafegoCSharp/Trafego1/Dockerfile'
        tags: |
          $(tag)
          latest

    - task: Docker@2
      displayName: Login to Azure Container Registry (ACR)
      inputs:
        command: login
        containerRegistry: 'your-acr-service-connection'

    - task: Docker@2
      displayName: Push Docker image to ACR
      inputs:
        command: push
        repository: 'youracr.azurecr.io/your-image-name'
        tags: |
          $(tag)
          latest
