// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Trafego1.Data.Contexts;

#nullable disable

namespace Trafego1.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240626224636_AddTrafego")]
    partial class AddTrafego
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trafego1.Models.Notificacoes", b =>
                {
                    b.Property<int>("NotificacoesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificacoesId"));

                    b.Property<string>("ServicoCliente")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ServicoEmergencia")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ServicoPolicial")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ServicoSaude")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("NotificacoesId");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("Trafego1.Models.Semaforos", b =>
                {
                    b.Property<int>("SemaforosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemaforosId"));

                    b.Property<string>("FluxoTrafego")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("SemaforosId");

                    b.ToTable("Semaforos");
                });

            modelBuilder.Entity("Trafego1.Models.Trafego", b =>
                {
                    b.Property<int>("TrafegoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrafegoId"));

                    b.Property<string>("AnaliseCongestionamento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("AnaliseVias")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CondicoesClimaticas")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("OtimizacaoRotas")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Rotas")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("TrafegoId");

                    b.ToTable("Trafegos");
                });
#pragma warning restore 612, 618
        }
    }
}
